src/org/jitsi/meet/test/DataChannelTest.java
src/org/jitsi/meet/test/StopVideoTest.java
src/org/jitsi/meet/test/util/TestUtils.java

This test ensures that we do not trigger TRACK_ADDED/TRACK_REMOVED events when remote participant mutes or unmutes his video.

test to check if we trigger TRACK_ADDED/REMOVED events on video mute

---

src/org/jitsi/meet/test/ConferenceMigrationTest.java

Jicofo with active health checks should detect failure faster.
To be merged only once https://github.com/jitsi/jicofo/pull/41 is merged and once we have page reload fixed in jitsi-meet.

Decreases disconnect timeout in conference migration.

---

src/org/jitsi/meet/test/ConferenceFixture.java
src/org/jitsi/meet/test/EndConferenceTest.java

Fixes the tests when PeerConnectionStatus test is scheduled after the EndConference test

Test participant conn status

---

src/org/jitsi/meet/test/util/MeetUIUtils.java

It looks like 'googSuspendBelowMinBitrate' = true can significantly
increase the time it takes for the video to unfreeze during the test.

Increase waiting timeout in PeerConnectionStatusTest

---

src/test/java/org/jitsi/meet/test/LipSyncTest.java

The `googEnableVideoSuspendBelowMinBitrate` flag is breaking our lipsync test because sending video is suspended and never reactivated. It could be due to several things: a problem in our padding termination (their padding is killed before it reaches our remote bitrate estimator), a problem in the old GCC implementation, or a problem in their padding budget calculation.

fix: Disable sendside video suspension for the LipSyncTest.

---

src/test/java/org/jitsi/meet/test/LockRoomTest.java

The invite modal UX has been changed to add a toggle link for
showing and hiding the fields to edit the room password. The
modal has also been converted to use react. These changes require
modifying LockRoomTest and how it searches for elements and sets
or removes the room password.

fix: change selectors and behavior for lock test

---

src/test/java/org/jitsi/meet/test/DataChannelTest.java

Related to issue [509](https://github.com/jitsi/lib-jitsi-meet/pull/509) "Make it possible to use WebSocket instead of DataChannel" in lib-jitsi-meet. Requested in this [comment](https://github.com/jitsi/lib-jitsi-meet/pull/509#issuecomment-309024836).
/CC @damencho

DataChannelTest: rework isDataChannelOpen() test based on new BridgeChannel

---

src/test/java/org/jitsi/meet/test/util/MeetUIUtils.java

Instead of assuming the thumbnail's video element is a direct
child of another element, perform a descendant search. This will
help keep the tests flexible while reactification work is ongoing.

ref(small-video): video element xpath as descendant not child

---

src/test/java/org/jitsi/meet/test/OneOnOneTest.java

- The toolbar display durations have been reduced to compensate
for a torture test machine that might be a little slow.
- The selector for the mousehover target, for showing remote
videos, has been changed to one that is guaranteed to be
available.

fix(1-on-1): adjust toolbar hide times, change hover selector

---

src/test/java/org/jitsi/meet/test/util/MeetUIUtils.java

With a recent tooltip update, tooltips no longer dismiss
from a toolbar button after the button is clicked. This
is intentional and a workaround is to move the mouse
off the button after click.

fix(follow-me): move mouse off toolbar after click

---

src/test/java/org/jitsi/meet/test/AudioOnlyTest.java
src/test/java/org/jitsi/meet/test/TestsRunner.java

These tests have the owner enable audio only, then verify video is
not display, then disable audio only, and finally verify video is
displayed.

feat(audio-only): Basic integration tests

---

src/test/java/org/jitsi/meet/test/SharedVideoTest.java

YouTube deprecated getVideoData() a while ago, and so the
video title can no longer be easily obtained. So instead,
rely on video id to check the correct video has been loaded.

fix(shared-video): check video id instead of title

---

src/test/java/org/jitsi/meet/test/PSNRTest.java
src/test/java/org/jitsi/meet/test/capture/VideoOperator.java

The method sometimes fails with: "java.lang.ClassCastException:
java.lang.Long cannot be cast to java.lang.Double".
I guess that if the value happens to be integer it can be Long instead
of Double. Make it Number given that it's only used in a debug log.

fix(VideoOperator): fix class cast exception

---

src/test/java/org/jitsi/meet/test/PSNRTest.java

Will fail the PSNRTest if it was explicitly included in the test to run.
SkippedException results in successful test run.
Give more details on what resources are missing.

fix(PSNRTest): do not skip, but fail if no files

---

src/test/java/org/jitsi/meet/test/base/AbstractBaseTest.java
src/test/java/org/jitsi/meet/test/base/FailureListener.java

Moves the failed configuration tests to the set of failed tests to be easily recognised in html report.

Records logs and screenshots when configuration fails.

---

src/test/java/org/jitsi/meet/test/base/Participant.java

Rename will not work for some cases. Unfortunately I can not explain
them exactly - maybe it was just wrong way of doing things. Previously
we used "copyFile" to do that. I want to give "moveFile" a try since it
will preserve some resources by not keeping two files.

fix(Participant): move file in takeScreenshot

---

src/test/java/org/jitsi/meet/test/web/WebParticipant.java

The tests were observed to sometimes fail with the "c" shortcut being
sent to the chat panel instead of the main video as intended.

fix: Attempts to fix an intermittent failure in the chat panel tests.

---

src/test/java/org/jitsi/meet/test/mobile/AndroidParticipantBuilder.java
src/test/java/org/jitsi/meet/test/mobile/MobileParticipantBuilder.java

App wait/package properties did not have the prefix. The capabilities
key was not stripped out of the prefix correctly. It worked, because
the two issues were present both at the same time, but i t was not
possible to override those capabilities.

fix(mobile): bug in parsing caps properties

---

src/test/java/org/jitsi/meet/test/LockRoomTest.java
src/test/resources/desktop/testng.xml

Now that Invite Modal is being removed, remove LockRoomTest
which exercised the modal's lock feature. Rename NewLockRoomTest
which also exercises the lock feature but in the Info Dialog.

ref(lock-room): replace LockRoomTest with NewLockRoomTest

---

src/test/java/org/jitsi/meet/test/web/WebTestBase.java

Our tests up till now have been working without TURN (our test deployments didn't have TURN support). Beta now as a TURN server because of the new bandwidth estimation test. This change might break some tests if left enabled by default.

ref: Disable TURN by default.

---

src/test/java/org/jitsi/meet/test/base/AbstractBaseTest.java
src/test/java/org/jitsi/meet/test/base/TestSettings.java

This is not a copying constructor - it will put the properties as
defaults which are treated in a special way by Properties's methods.
You can not remove a default property for example. They are also not
visible when debugging in some IDEs.
https://docs.oracle.com/javase/7/docs/api/java/util/Properties.html#Properties(java.util.Properties)

fix(Properties): do not use new Properties(properties)

---

src/test/java/org/jitsi/meet/test/pageobjects/mobile/permissions/PermissionsAlert.java

It turns out that the xpath search was actually doing a search by id (@resource-id == id on Android, @name == id on iOS).

ref(PermissionsAlert): search by id

---

src/test/java/org/jitsi/meet/test/mobile/MobileParticipant.java
src/test/java/org/jitsi/meet/test/mobile/base/AndroidParticipantOptions.java

It turns out that Android driver will not simply accept the package name
as the "app" capability to run the app if it comes pre-installed on
the device (in contrary to what the iOS driver does). Because of that we
need to provide default values for both package and activity
capabilities.
Rename the MobileParticipant's app field to something more meaningful.

fix(AndroidParticipantOptions): provide default app/package

---

src/test/java/org/jitsi/meet/test/AvatarTest.java
src/test/java/org/jitsi/meet/test/ContactListTest.java
src/test/java/org/jitsi/meet/test/FilmstripOnlyTest.java
src/test/java/org/jitsi/meet/test/OneOnOneTest.java
src/test/java/org/jitsi/meet/test/RingOverlayTest.java
src/test/java/org/jitsi/meet/test/SwitchVideoTest.java
src/test/java/org/jitsi/meet/test/pageobjects/web/Toolbar.java
src/test/java/org/jitsi/meet/test/pageobjects/web/ToolbarV2.java
src/test/java/org/jitsi/meet/test/web/WebParticipant.java
src/test/java/org/jitsi/meet/test/web/WebTestBase.java

I've left in the old toolbar page object. I'll be getting rid of it when the old toolbar is removed from jitsi-meet. I suppose as long as the old toolbar exists I'd prefer to keep it present so it's testable.

feat(toolbar): new page object for new toolbar

---

src/test/java/org/jitsi/meet/test/mobile/MobileParticipant.java

The hack to click room name input multiple times is no longer needed.

fix(MobileParticipant): remove hack

---

src/test/java/org/jitsi/meet/test/mobile/MobileParticipant.java
src/test/java/org/jitsi/meet/test/mobile/base/MobileParticipantFactory.java
src/test/java/org/jitsi/meet/test/pageobjects/base/TestHint.java
src/test/java/org/jitsi/meet/test/pageobjects/mobile/ConferenceView.java
src/test/java/org/jitsi/meet/test/pageobjects/mobile/ToolbarView.java

Fixes a SetupConferenceTest failure on Android caused by the fact that there's no clickable "Conference" element in jitsi-meet.

fix(Android): can not find "conference" element

---

src/test/java/org/jitsi/meet/test/web/WebTestBase.java

Before I tried closing the info dialog as tests needed. But that proved to be flaky. This time try to close info dialog after ensuring participant joins, which seems like the most often used way to make a participant join a call.

fix(info): always close info dialog after ensuring participant join

---

src/test/java/org/jitsi/meet/test/web/WebTestBase.java

With latest chrome update (v66, v65) we see sometimes on screenshots and on video that the browser is stuck on the permissions screen and never joins the room. We skip the first wait to join failure and we retry second time.

Retry joining a muc on first failure.

---

src/test/java/org/jitsi/meet/test/base/AbstractBaseTest.java
src/test/java/org/jitsi/meet/test/base/ParticipantHelper.java
src/test/java/org/jitsi/meet/test/web/WebTestBase.java

Closing the participant will make sure chrome is closed/quit and we move to another grid node.

Closes the participant for the workaround of cb98fee.

---

src/test/java/org/jitsi/meet/test/util/MeetUIUtils.java

Now the video or avatar will be visible under the name but with
transparency. As such checking if it is not displayed will fail.

fix(filmstrip): do not check video or avatar is hidden if name displays

---

src/test/java/org/jitsi/meet/test/base/JitsiMeetUrl.java

To configure against what server these tests are executed, a URL is provided
through system properties, like this:
mvn test -Djitsi-meet.instance.url="https://meet.example.com"
This commit prevents failures when this URL ends with a slash. In other words,
this is now also acceptable:
mvn test -Djitsi-meet.instance.url="https://meet.example.com/"

improvement: allow jitsi-meet instance URL to have a trailing slash.

---

src/test/java/org/jitsi/meet/test/mobile/base/MobileParticipantFactory.java

~~I don't know how to run the tests locally so I'm just gonna run them here...~~
The current tests do not set an implicit wait timeout. The tests assume then that overlays and dialogs will display immediately. It could be that there is a display delay, so actions to dismiss a dialog or overlay doesn't happen at the right time and blocks further test progress.
That's the guess...

fix(mobile): set implicit wait for variable display timings

---

src/test/java/org/jitsi/meet/test/mobile/MobileParticipant.java

Since the calendar tab changes we now have 2 permission popups on start so we need to click allow for both.
Required by https://github.com/jitsi/jitsi-meet/pull/3095 which defaults to the Calendar tab and thus may cause the appearance of the Calendar permission prompt on startup.

[RN] Allow calendar permission on start

---

src/test/java/org/jitsi/meet/test/mobile/MobileParticipant.java

No permissions are requested any longer. Camera and mic permissions are
now requeted when joining.

fix(MobileParticipant): fix permissions on the welcome page

---

src/test/java/org/jitsi/meet/test/TileViewTest.java

Instead of leaving tile view enabled on pin or etherpad open, but
changing to filmstrip view, the UX is now pinning or opening etherpad
disables tile view.

fix(tile-view): update tests for exiting tile view on pin and etherpad

---

src/test/java/org/jitsi/meet/test/EtherpadTest.java

There can be a delay between the etherpad inner body being
displayed and being editable.

fix(etherpad): verify etherpad can be edited before editing

---

src/test/java/org/jitsi/meet/test/util/TestUtils.java

This is so they can all have the StaleElementException
handling.

ref: combine waits for element (not) displayed into method

---

src/test/java/org/jitsi/meet/test/LockRoomTest.java

enterParticipantInLockedRoom is being flaky right now.
Screenshots show the password input is not cleared after
attempting to submit a known bad password, indicating
maybe the known password was never submitted.

fix(lock-room): wait for password submit to be clickable

---

src/test/java/org/jitsi/meet/test/DialInAudioTest.java
src/test/java/org/jitsi/meet/test/web/WebParticipant.java

If that fail we can evaluate test results and differentiate failures, did it failed cause participant didn't join or something went wrong after that.

Waits for the remote participant to join.

---

scripts/push_psnr_results.py

we now push extra data because jigmi supports psnr coming from multiple
'projects' in a single graph

adapt to jigmi changes

---

src/test/java/org/jitsi/meet/test/SharedVideoTest.java

This is triggering stale element exceptions right now.

fix(shared-video): stop returning unused objects when running js

---

src/test/java/org/jitsi/meet/test/util/MeetUtils.java

Changed APP.conference.getConnectionState() to APP.conference.getP2PConnectionState() to fix Peer2Peer check.

Fix for Peer2Peer check

---

src/test/java/org/jitsi/meet/test/pageobjects/web/SecurityDialog.java

Trying to fix a failure we see from time to time in the tests.

fix: Adds a wait after opening security dialog on setting password.

---

src/test/java/org/jitsi/meet/test/PreJoinTest.java

We are seeing random failures for join button being not disabled.
The response of the disco-info does not contain the required display name field.

Skips prejoin test by default.

---

src/test/java/org/jitsi/meet/test/LobbyTest.java
src/test/java/org/jitsi/meet/test/pageobjects/web/KnockingParticipantList.java

When participant leaves we can be checking the dialog in the moment it is about to hide.
org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
....
org.openqa.selenium.remote.RemoteWebElement.findElementById(RemoteWebElement.java:221)
org.openqa.selenium.By$ById.findElement(By.java:188)
org.openqa.selenium.remote.RemoteWebElement.findElement(RemoteWebElement.java:181)
org.jitsi.meet.test.pageobjects.web.KnockingParticipantList.lambda$getParticipants$0(KnockingParticipantList.java:94)
java.util.ArrayList.forEach(ArrayList.java:1257)
org.jitsi.meet.test.pageobjects.web.KnockingParticipantList.getParticipants(KnockingParticipantList.java:88)
org.jitsi.meet.test.LobbyTest.testLobbyUserLeaves(LobbyTest.java:284)
...

fix: Fixes another StaleElementReferenceException in lobby tests.

---

src/test/java/org/jitsi/meet/test/pageobjects/web/SecurityDialog.java

It can happen that the element is removed  from the page while getting the validationMessage attribute.

fix: Tries to fix StaleElement error.

---

pom.xml

When I was trying to run `./scripts/malleus.sh` with Chrome driver I got the following error:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
Adding the dependency fixes the issue and logs get printed.

fix: Add SLF4J logger implementation dependency

---

src/test/java/org/jitsi/meet/test/MalleusJitsificus.java

This overrides the jitsi-meet-torture interval setting of 1500 back to the lib-jitsi-meet default setting of 10000.
I'd rather leave it blank entirely, and thus use the site's default value, but unfortunately the current structure of the jitsi-meet-torture code doesn't allow that.

Set pcStatsInterval on Malleus tests.

---

src/test/java/org/jitsi/meet/test/pageobjects/web/SettingsDialog.java

This change is required to support the new version of atlaskit checkbox component in jitsi-meet. The new compontent uses a `appearance: none` css style wich causes `WebElement.click()` to fail with `ElementNotInteractableException` because it is not visible to Selenium. The checkbox is keyboard and mouse accessible in the browser though. The PR is a requirement for https://github.com/jitsi/jitsi-meet/pull/8423 to land.

Change test to support new atlaskit version of checkbox

---

src/test/java/org/jitsi/meet/test/StartMutedTest.java

This PR - https://github.com/jitsi/jitsi-meet/pull/8716 changes the behavior of startAudioMuted/startVideoMuted settings. Since tracks are not added to the peerconnection, no media will be sent by participant2 when it joins the call. Earlier, because the tracks were muted after join, audio packets (silence) were sent out by participant2.

fix(StartMutedTest): Do not check for send media on p2 after join.

---

src/test/java/org/jitsi/meet/test/SharedVideoTest.java

We used to have cancel button where we cancel the stopping, and skipping that we were stopping it where we expect it to be running.

fix: SharedVideoTest and re-enables it.

---

src/test/java/org/jitsi/meet/test/DesktopSharingTest.java

Now that audio track is not added on startWithAudioMuted, participant2 (that starts audio muted) will not be sending any media when participant1 is in audio-only mode.

fix(DesktopSharingTest): Do not check for send media on p2.

---

src/test/java/org/jitsi/meet/test/DesktopSharingTest.java

They were failing because of a lastN issue that has now been fixed in the bridge - https://github.com/jitsi/jitsi-videobridge/commit/f540df412cdc12b7f34e7eae16099c0e2c8ec413.

Fix: Re-enable DesktopSharingTest.

---

src/test/java/org/jitsi/meet/test/DesktopSharingTest.java

This is known that the slowness comes from the bridge and after we fix it there will revert this change.

fix: Temporary bump wait time.

---

src/test/java/org/jitsi/meet/test/IFrameAPITest.java

Sometimes the third becomes dominant too early and the test fails later waiting to become dominant speaker event.

fix: Fix testSetLargeVideoParticipant and dominant speaker events.

---

src/test/java/org/jitsi/meet/test/DialInAudioTest.java

00:33:49 [10] TestFailure:
00:33:49 org.openqa.selenium.WebDriverException: unknown error: session deleted because of page crash
00:33:49 from unknown error: cannot determine loading status
00:33:49 from tab crashed
00:33:49   (Session info: chrome=93.0.4577.82)
00:33:49 Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
00:33:49 System info: host: 'jenkins.jitsi.net', ip: '52.41.182.55', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1025-aws', java.version: '1.8.0_265'
00:33:49 Driver info: org.openqa.selenium.remote.RemoteWebDriver
00:33:49 Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 93.0.4577.82, chrome: {chromedriverVersion: 93.0.4577.63 (ff5c0da2ec0ad..., userDataDir: /tmp/.com.google.Chrome.nHmuRj}, …

feat: Skips failing dial-in tests on page crash.

---

src/test/java/org/jitsi/meet/test/LobbyTest.java
src/test/java/org/jitsi/meet/test/base/ParticipantHelper.java
src/test/java/org/jitsi/meet/test/web/WebTestBase.java

Seems like from time to time we quickly hangup one of the participants in testConferenceEndedInLobby test, and it stays in the room with lobby enabled. In that case when participant 1 in next test tries to join fails on isInMuc check as there is Lobby. We close it deciding that chrome crashed and try again. The problem was that our close is wrong and the indexes are messed up and participant2 becomes participant1 and everything starts failing :)
Fixes the close which is used only in that rare case we consider as chrome crash ... we may eventually get rid of that workaround as we no longer see chrome crashes.

fix: Fixes failing lobby test and missing first participant.

---

src/test/java/org/jitsi/meet/test/MuteTest.java
src/test/java/org/jitsi/meet/test/web/WebTestBase.java

fix(MuteTest): Wait for p2 to connect before starting share on p1.
fix: Always override displayName when adding a participant to the call.

Fix mute test

---

src/test/java/org/jitsi/meet/test/LobbyTest.java

Remove second participant notification check for action from participants pane. Check only that participant 3 is admitted / rejected

fix(lobby) Remove notification check on admit/ reject

---

src/test/java/org/jitsi/meet/test/DisplayNameTest.java

Based on the fact that we migrated defaultRemoteDisplayName and defaultLocalDisplayName from interfaceConfig to config

feat(config) replaced interfaceConfig with config on DisplayNameTest

---

src/test/java/org/jitsi/meet/test/DisableSelfViewTest.java
src/test/java/org/jitsi/meet/test/pageobjects/web/Notifications.java

To avoid StaleElementReferenceException.

fix: Adds a retry for closing notifications.

---

src/test/java/org/jitsi/meet/test/BreakoutRoomsTest.java

Added startWithAudioMuted to prevent reordering in the participants pane

fix(breakout-rooms) Start meeting with audio muted

---

scripts/malleus.sh

This will allow to launch `malleus.sh` without any arguments.
Before this, `malleus.sh` would fallback to https://github.com/jitsi/jitsi-meet-torture/blob/master/scripts/malleus.sh#L130 and display `usage`.
Closes #489

fix: Run malleus.sh without any arguments

---

src/test/java/org/jitsi/meet/test/BreakoutRoomsTest.java

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
java.util.ArrayList.rangeCheck(ArrayList.java:659)
java.util.ArrayList.get(ArrayList.java:435)
org.jitsi.meet.test.BreakoutRoomsTest.lambda$testLeaveRoom$9(BreakoutRoomsTest.java:164)
org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
org.jitsi.meet.test.util.TestUtils.waitForCondition(TestUtils.java:545)
org.jitsi.meet.test.util.TestUtils.waitForCondition(TestUtils.java:559)
org.jitsi.meet.test.BreakoutRoomsTest.testLeaveRoom(BreakoutRoomsTest.java:163)

fix: Fixes OutOfBoundsException in breakout tests.

---

src/test/java/org/jitsi/meet/test/web/WebParticipantFactory.java

Since Chrome 102 we see strange random crashes when running chrome. Reporting to chromium and it seems it is triggered inside `if (VLOG_IS_ON(3))` block. At the moment those logs are being cleared once session is over or chrome crashes, so disabling them for now. Thanks to @JonathanLennox for digging into it.

fix: Disable chrome debug logging.

---

src/test/java/org/jitsi/meet/test/StartMutedTest.java

It can happen that both join almost at the exact time and jicofo will mute p1 where we expect to mute p2.

fix: Fixes startmuted test.

---

src/test/java/org/jitsi/meet/test/StartMutedTest.java

because the first 2 participants are not necessarily invited in order.

fix: Test with startMuted=2

---

src/test/java/org/jitsi/meet/test/web/WebParticipant.java

The exception is otherwise always visible in iframeAPI tests.

fix: Skip error stack trace.

---

src/test/java/org/jitsi/meet/test/LockRoomTest.java

After updating dialog UI we see random failures. One is where we send wrong pass and do not join the call. The other one is: Unable to locate element: {"method":"css selector","selector":"#modal\-dialog\-ok\-button"}

fix: Fixes flaky lock room test.

---

src/test/java/org/jitsi/meet/test/AudioVideoModerationTest.java
src/test/java/org/jitsi/meet/test/pageobjects/web/Notifications.java

Sometimes the join notifications can be on the way of hovering or clicking buttons. Dismissing it to make sure this does not happen randomly.

fix: Adds method to dismiss any join notification.

---

src/test/java/org/jitsi/meet/test/AudioVideoModerationTest.java
src/test/java/org/jitsi/meet/test/pageobjects/web/ParticipantsPane.java

Adds a wait after opening the participants pane so all elements even the hidden ones are in place before trying to mouse the mouse over them.

feat: Adds debug print in ParticipantsPane.

---

src/test/java/org/jitsi/meet/test/base/Participant.java

org.openqa.selenium.JavascriptException: javascript error: APP is not defined
(Session info: headless chrome=119.0.6045.123)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03' System info: host: '462c96113664', ip: '172.17.0.12', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-1030-oracle', java.version: '11.0.19' Driver info: org.openqa.selenium.remote.RemoteWebDriver Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 119.0.6045.123, chrome: {chromedriverVersion: 119.0.6045.105 (38c72552c5e..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:30787}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, …

fix: Fixes NPE on failure to join a conference.

---

src/test/java/org/jitsi/meet/test/StartMutedTest.java

Only add the first participant as audio and video muted. When p1 and p2 join muted, p1 and p2 unute their audio and video sequentially, the media from p1 reaches before signaling for p1 sources reaches p2. The browser creates a receiver when it receives a packet on certain mid/ssrc. So when the client tries to set the remote description after signaling is received, this results in a collision causing the setRemoteDescription call to fail with the error: Error: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Failed to add remote stream ssrc: 1981416894 to {mid: 1, media_type: video}

fix(StartMutedTest): Modify startWithAudioVideoMutedCanUnmute.

---

src/test/java/org/jitsi/meet/test/CodecSelectionTest.java

Do not assume defaults since different deployments have different settings.

fix(CodecSelectionTest) Configure codec preference explicitly.

---

src/test/java/org/jitsi/meet/test/SharedVideoTest.java

We started seeing errors in the tests. Seems to be only from certain IPs running the tests regularly.
[modules/UI/videolayout/VideoContainer.js] <HTMLVideoElement.<anonymous>>:  abort handler was called for the large video.
[react/features/shared-video/components/web/AbstractVideoManager.ts] <P7.onError>:  Error in the video player 150 Check error code at https://developers.google.com/youtube/iframe_api_reference#onError

fix: Drops youtube sharing video tests.

---

src/test/java/org/jitsi/meet/test/util/MeetUIUtils.java

This PR is related with jitsi/jitsi-meet#14997
It fixes the test to check the related PR correctly.
`Aria-label` is not static for the participant button after the update. So, looking for the whole match doesn't work. This PR allows to find the matching tag by checking the match at the beginning.

fix(getAccessibilityCSSSelector): Finding the matching aria-label

---

src/test/java/org/jitsi/meet/test/OneOnOneTest.java
src/test/java/org/jitsi/meet/test/web/WebParticipant.java

This PR is related with https://github.com/jitsi/jitsi-meet/pull/15054
It fixes the test tool to check the related PR correctly.
There is a new config parameter (`config.toolbarConfig.alwaysVisible`) to make the toolbar always visible during tests. The old one doesn't work anymore. So, the test tool cannot find some buttons in some conditions if the old one is used.

fix: Make the toolbar visible by using the new config parameter

---

.github/workflows/maven.yml

v2 is being deprecated in February.

Update actions/cache in Github workflow.
