src/org/jitsi/meet/test/ConferenceFixture.java
src/org/jitsi/meet/test/LastNTest.java
src/org/jitsi/meet/test/TestsRunner.java
src/org/jitsi/meet/test/util/MeetUIUtils.java

depends on https://github.com/jitsi/jitsi-meet/pull/519

add test for Last N feature

---

src/org/jitsi/meet/test/AvatarTest.java
src/org/jitsi/meet/test/StartMutedTest.java

depends on https://github.com/jitsi/jitsi-meet/pull/520

do not use "update" button in tests

---

src/org/jitsi/meet/test/FollowMeTest.java
src/org/jitsi/meet/test/TestsRunner.java

Follow me tests (fixed)

---

src/org/jitsi/meet/test/LockRoomTest.java

Tests https://github.com/jitsi/lib-jitsi-meet/pull/227 and https://github.com/jitsi/jitsi-meet/pull/821.

Adds tests for updating lock state room to participants.

---

src/org/jitsi/meet/test/AvatarTest.java
src/org/jitsi/meet/test/ConferenceFixture.java
src/org/jitsi/meet/test/DesktopSharingImitationTest.java
src/org/jitsi/meet/test/EndConferenceTest.java
src/org/jitsi/meet/test/FollowMeTest.java
src/org/jitsi/meet/test/LockRoomTest.java
src/org/jitsi/meet/test/VideoLayoutTest.java
src/org/jitsi/meet/test/util/MeetUIUtils.java

Depends on redesign done in the same branch on jitsi meet.

Fixes various tests broken by the redesign

---

src/org/jitsi/meet/test/DisplayNameTest.java

Fixed "changeDisplayName" test. This is the same as PR#36. This one just uses different branch name.

Adds a PR to test some PRs in jitsi-meet.

---

src/org/jitsi/meet/test/AvatarTest.java
src/org/jitsi/meet/test/DisplayNameTest.java
src/org/jitsi/meet/test/MuteTest.java
src/org/jitsi/meet/test/StartMutedTest.java
src/org/jitsi/meet/test/StopVideoTest.java
src/org/jitsi/meet/test/util/MeetUIUtils.java
src/org/jitsi/meet/test/util/TestUtils.java

A second copy of the latest changes in order to be tested agains another Jitsi Meet PR. DO NOT MERGE.

Blue badges

---

src/org/jitsi/meet/test/LockRoomTest.java

Updated room lock test suite to support new lock/unlock functionality via invite dialog

Fix lock room test suite

---

src/org/jitsi/meet/test/AvatarTest.java
src/org/jitsi/meet/test/SwitchVideoTest.java
src/org/jitsi/meet/test/util/MeetUIUtils.java

After clicking remote or local video give time for the video/avatar to change.

---

src/org/jitsi/meet/test/FollowMeTest.java
src/org/jitsi/meet/test/util/TestUtils.java

Fix the test from https://github.com/jitsi/jitsi-meet/pull/1107

Add new method to TestUtils; fix the test

---

src/org/jitsi/meet/test/FollowMeTest.java

Fix the tests for https://github.com/jitsi/jitsi-meet/pull/1128

Fix the tests

---

src/test/java/org/jitsi/meet/test/util/MeetUtils.java

Uses the new getParticipantConnectionStatus method for checking peer connection status.

Uses getParticipantConnectionStatus method for peer connection status.

---

src/test/java/org/jitsi/meet/test/RingOverlayTest.java

Fixes automatic PR testing for https://github.com/jitsi/jitsi-meet/pull/1397.

Fix CSS issue

---

src/test/java/org/jitsi/meet/test/FollowMeTest.java

Fixes tests against PR: https://github.com/jitsi/jitsi-meet/pull/1473

Fixes filmstrip commands test

---

src/test/java/org/jitsi/meet/test/FollowMeTest.java
src/test/java/org/jitsi/meet/test/util/MeetUIUtils.java

https://github.com/jitsi/jitsi-meet/pull/1482

Approach consistent filmstrip naming

---

src/test/java/org/jitsi/meet/test/OneOnOneTest.java

jitsi-meet will have changes that have the remote videos of
the filmstrip display with the toolbars. The 1-on-1 tests have
to make sure the toolbars are not set to show all the time
and also wait for them to disappear. The test for showing
remote videos while sharing video was removed because sharing
video docks the toolbar, so remote videos always display. That
test has been replaced with a test to ensure remote videos
stay displayed while being hovered over.

fix(1-on-1): update tests for displaying videos with toolbar

---

src/test/java/org/jitsi/meet/test/util/MeetUIUtils.java

React can re-render a button so its reference is no more valid, so we retry several times doing that.

Implements clicking on toolbar buttons ignoring stale exceptions.

---

src/test/java/org/jitsi/meet/test/base/FailureListener.java

Do not try to create if the directory exists.

fix(FailureListener): fix mkdir log

---

src/test/java/org/jitsi/meet/test/pageobjects/web/InfoDialog.java

A better solution has to be thought of and implemented. For now
go with the approach of not chaining in case the element has
become stale from a react re-render.

fix(info): for now avoid chained look ups to avoid stale elements

---

src/test/java/org/jitsi/meet/test/ActiveSpeakerTest.java
src/test/java/org/jitsi/meet/test/AvatarTest.java
src/test/java/org/jitsi/meet/test/ConferenceMigrationTest.java
src/test/java/org/jitsi/meet/test/DisplayNameTest.java
src/test/java/org/jitsi/meet/test/FollowMeTest.java
src/test/java/org/jitsi/meet/test/JibriTest.java
src/test/java/org/jitsi/meet/test/LipSyncTest.java
src/test/java/org/jitsi/meet/test/OneOnOneTest.java
src/test/java/org/jitsi/meet/test/ReloadTest.java
src/test/java/org/jitsi/meet/test/SharedVideoTest.java
src/test/java/org/jitsi/meet/test/SinglePortTest.java
src/test/java/org/jitsi/meet/test/StartMutedTest.java
src/test/java/org/jitsi/meet/test/StopVideoTest.java
src/test/java/org/jitsi/meet/test/VideoLayoutTest.java
src/test/java/org/jitsi/meet/test/base/Participant.java
src/test/java/org/jitsi/meet/test/capture/VideoOperator.java
src/test/java/org/jitsi/meet/test/mobile/MobileParticipant.java
src/test/java/org/jitsi/meet/test/util/TestUtils.java
src/test/java/org/jitsi/meet/test/web/WebParticipant.java
src/test/java/org/jitsi/meet/test/web/WebTestBase.java

Mobile is not capable of executing any JavaScript code and probably never will be, so move away any code that depends on that to the WebParticipant.

ref(Participant): mobile does not execute scripts

---

src/test/java/org/jitsi/meet/test/BandwidthEstimationTest.java
src/test/java/org/jitsi/meet/test/util/MeetUtils.java

feat: Adds more networks (and a minor fix)

---

src/test/java/org/jitsi/meet/test/ActiveSpeakerTest.java
src/test/java/org/jitsi/meet/test/AudioOnlyTest.java
src/test/java/org/jitsi/meet/test/AvatarTest.java
src/test/java/org/jitsi/meet/test/LastNTest.java
src/test/java/org/jitsi/meet/test/MuteTest.java
src/test/java/org/jitsi/meet/test/ReloadTest.java
src/test/java/org/jitsi/meet/test/StartMutedTest.java
src/test/java/org/jitsi/meet/test/StopVideoTest.java
src/test/java/org/jitsi/meet/test/base/Participant.java
src/test/java/org/jitsi/meet/test/mobile/MobileParticipant.java
src/test/java/org/jitsi/meet/test/pageobjects/Filmstrip.java
src/test/java/org/jitsi/meet/test/pageobjects/web/WebFilmstrip.java
src/test/java/org/jitsi/meet/test/util/MeetUIUtils.java
src/test/java/org/jitsi/meet/test/web/WebParticipant.java
src/test/java/org/jitsi/meet/test/web/WebTestBase.java

I had separated the changes in different commits. If you prefer I can do separate PRs.

Fix audioonly clients

---

src/test/java/org/jitsi/meet/test/DisplayNameTest.java

Creating this new PR to match the jitsi-meet PR name so then CI will run on this.
Original PR: https://github.com/jitsi/jitsi-meet-torture/pull/176

Add timeout for persitency check before reload

---

src/test/java/org/jitsi/meet/test/pageobjects/mobile/ToolbarView.java
src/test/java/org/jitsi/meet/test/pageobjects/mobile/WelcomePageView.java
src/test/java/org/jitsi/meet/test/pageobjects/web/Toolbar.java

This brings the value of accessibility labels in line with the changes introduced
by https://github.com/jitsi/jitsi-meet/pull/3071

chore(i18n): update accessibility labels

---

pom.xml
src/test/java/org/jitsi/meet/test/mobile/base/MobileParticipantFactory.java
src/test/java/org/jitsi/meet/test/pageobjects/base/TestHint.java
src/test/java/org/jitsi/meet/test/pageobjects/mobile/base/AbstractMobilePage.java

Required for https://github.com/jitsi/jitsi-meet/pull/3508

RN 57 related stuff

---

src/test/java/org/jitsi/meet/test/DialInAudioTest.java
src/test/java/org/jitsi/meet/test/LockRoomTest.java
src/test/java/org/jitsi/meet/test/MuteTest.java
src/test/java/org/jitsi/meet/test/base/Participant.java
src/test/java/org/jitsi/meet/test/mobile/MobileParticipant.java
src/test/java/org/jitsi/meet/test/pageobjects/base/RemoteParticipant.java
src/test/java/org/jitsi/meet/test/pageobjects/web/InfoDialog.java
src/test/java/org/jitsi/meet/test/pageobjects/web/ModalDialogHelper.java
src/test/java/org/jitsi/meet/test/pageobjects/web/SettingsDialog.java
src/test/java/org/jitsi/meet/test/pageobjects/web/WebRemoteParticipant.java
src/test/java/org/jitsi/meet/test/util/MeetUIUtils.java
src/test/java/org/jitsi/meet/test/util/TestUtils.java
src/test/java/org/jitsi/meet/test/web/WebParticipant.java
src/test/resources/desktop/testng.xml

Depends on https://github.com/jitsi/jitsi-meet/pull/3778

Dial in test

---

src/test/java/org/jitsi/meet/test/web/WebParticipant.java

Depends on https://github.com/jitsi/jitsi-meet/pull/4260

Disable analytics

---

src/test/java/org/jitsi/meet/test/mobile/MobileParticipant.java

Use new API for sending key event.

fix(android): join room

---

src/test/java/org/jitsi/meet/test/TileViewTest.java
src/test/java/org/jitsi/meet/test/util/MeetUIUtils.java

Essentially reverting
e211faaad5bbaf13c80899cbbd165fa19e7c6ae7

change tile-view test back to single-click to pin

---

resources/fakeAudioStream_license.txt

(Rather than a horrifying scream.)

Change audio track to the Helium article from Wikipedia.

---

scripts/malleus.sh
src/test/java/org/jitsi/meet/test/MalleusJitsificus.java
src/test/java/org/jitsi/meet/test/web/WebTestBase.java

This is a cleaned-up version of @gpolitis 's malleus patches, along with some enhancements by @bgrozev .

Malleus improvements

---

src/test/java/org/jitsi/meet/test/LockRoomDigitsOnlyTest.java
src/test/java/org/jitsi/meet/test/pageobjects/web/SecurityDialog.java
src/test/java/org/jitsi/meet/test/util/ValidationError.java
src/test/resources/desktop/testng.xml

Depends on https://github.com/jitsi/jitsi-meet/pull/7372

Add test for digits only room lock

---

src/test/java/org/jitsi/meet/test/LobbyTest.java
src/test/java/org/jitsi/meet/test/pageobjects/web/LobbyScreen.java

When there are 3 participants in a call and lobby is enabled we want to make sure the call continues to have 3 participants.

feat: Adds one more lobby test case.

---

src/test/java/org/jitsi/meet/test/LastNTest.java
src/test/java/org/jitsi/meet/test/util/MeetUIUtils.java

Increase the wait time for waitForRemoteVideo from 5 to 10 since it can sometimes take longer for the bridge to switch the videos that it is sending when lastN kicks in.

fix: Update lastN test.

---

scripts/malleus.sh

Also fix spelling of a parameter.

Fix malleus script backward-compatibility (six-argument); output new usage.

---

pom.xml
scripts/blip.sh
src/test/java/org/jitsi/meet/test/MalleusJitsificus.java
src/test/java/org/jitsi/meet/test/util/Blip.java
src/test/java/org/jitsi/meet/test/web/WebParticipant.java

The actual fix is here 5c58e17f6c326eda2924a711c41a736226bf06ee and consists of bumping the getBridgeIp timeout to 30s. The rest is some minor refactoring and cleanup.

Blips with load test fixes

---

src/test/java/org/jitsi/meet/test/MalleusJitsificus.java
src/test/java/org/jitsi/meet/test/util/Blip.java

I refactored the code so that we can pull any exceptions that happened from the participant thread, and fail the overall test when it finishes.

Fail malleus if the participant fails

---

src/test/java/org/jitsi/meet/test/SharedVideoTest.java

fix: Fixes SharedVideoTest.

---

scripts/malleus.sh
src/test/java/org/jitsi/meet/test/MalleusJitsificus.java
src/test/java/org/jitsi/meet/test/web/WebParticipant.java

Makes malleus execution asynchronous to make this cleaner.

Add code to switch speakers in Malleus.

---

src/test/java/org/jitsi/meet/test/LobbyTest.java

There are cases where checks are made before the actual lobby room is joined when things happen to quickly.

fix: Waits for lobby room to be joined.

---

src/test/java/org/jitsi/meet/test/pageobjects/web/ParticipantsPane.java
src/test/java/org/jitsi/meet/test/pageobjects/web/Toolbar.java

@damencho Does this work for you?
https://github.com/jitsi/jitsi-meet/pull/8921

fix: Fix toolbar strings for WCAG. 

---

src/test/java/org/jitsi/meet/test/AudioVideoModerationTest.java
src/test/java/org/jitsi/meet/test/pageobjects/web/Notifications.java
src/test/java/org/jitsi/meet/test/pageobjects/web/ParticipantsPane.java

Fixed some timeout exceed issues, typos and removed some unused methods.

fix(av-moderation) test fixes and updates

---

src/test/java/org/jitsi/meet/test/IFrameAPITest.java
src/test/java/org/jitsi/meet/test/pageobjects/web/Toolbar.java

fix(iframeAPITest) Updated toolbar button string

---

src/test/java/org/jitsi/meet/test/AudioVideoModerationTest.java
src/test/java/org/jitsi/meet/test/pageobjects/base/RemoteParticipant.java
src/test/java/org/jitsi/meet/test/pageobjects/web/Notifications.java
src/test/java/org/jitsi/meet/test/pageobjects/web/ParticipantsPane.java
src/test/java/org/jitsi/meet/test/pageobjects/web/WebRemoteParticipant.java

Added tests for:
- Ask to Unmute without moderation
- Remove from whitelist

fix(av-moderation) Added more tests

---

src/test/java/org/jitsi/meet/test/pageobjects/web/ParticipantsPane.java

Changed tests to use test id instead of accessibility label

refactor(participants-pane) Updated tests to use test id

---

src/test/java/org/jitsi/meet/test/pageobjects/web/SettingsDialog.java

linked PR https://github.com/jitsi/jitsi-meet/pull/10345
updated tests with new UI changes

feat: (moderate-reaction-sounds) moved settings from 'More' to 'Moderator' tab

---

src/test/java/org/jitsi/meet/test/pageobjects/web/SettingsDialog.java

Reverts jitsi/jitsi-meet-torture#459

Revert "feat: (moderate-reaction-sounds) moved settings from 'More' to 'Moderator' tab"

---

src/test/java/org/jitsi/meet/test/PreJoinTest.java
src/test/java/org/jitsi/meet/test/web/WebParticipant.java

Updated the `preJoin` tests to match the latest `config.js` changes in `jitsi-meet` version `6726`.

fix(preJoin): Configuration parameters for preJoin scenarios

---

src/test/java/org/jitsi/meet/test/web/WebParticipantFactory.java
src/test/java/org/jitsi/meet/test/web/WebParticipantOptions.java

Fixes issue when using original-trial that depend on using the domain name while testing with chrome for a particular host(ip-address).

feat: Adds new option to pass resolver rules.

---

src/test/java/org/jitsi/meet/test/JibriStreamResolutionTest.java
src/test/java/org/jitsi/meet/test/util/TestUtils.java

fix: Updates jibri tests with messages and wait longer for joining jibri

---

src/test/java/org/jitsi/meet/test/AudioOnlyTest.java
src/test/java/org/jitsi/meet/test/AvatarTest.java
src/test/java/org/jitsi/meet/test/FollowMeTest.java
src/test/java/org/jitsi/meet/test/IFrameAPIBase.java
src/test/java/org/jitsi/meet/test/IFrameAPICommandsTest.java
src/test/java/org/jitsi/meet/test/IFrameAPIFunctionsTest.java
src/test/java/org/jitsi/meet/test/IFrameAPIGeneral.java
src/test/java/org/jitsi/meet/test/OneOnOneTest.java
src/test/java/org/jitsi/meet/test/SwitchVideoTest.java
src/test/java/org/jitsi/meet/test/TileViewTest.java

Disable it on the tests that require only 1 participant on stage

fix(stage-filmstrip) Disable stage filmstrip on some tests

---

src/test/java/org/jitsi/meet/test/AudioVideoModerationTest.java
src/test/java/org/jitsi/meet/test/util/MeetUIUtils.java

- ref: Remove code duplication.
- Assert the expected mute state early.

Assert the expected mute state early, remove code duplication.

---

scripts/malleus.sh
src/test/java/org/jitsi/meet/test/MalleusJitsificus.java

Depends on new load-test features in https://github.com/jitsi/jitsi-meet-load-test.

Load test multiple clients per tab

---

src/test/java/org/jitsi/meet/test/DesktopSharingTest.java

Will be adding separate testcases for the multi-stream mode once its enabled by default in the code.

Disable multi-stream mode for screenshare.

---

src/test/java/org/jitsi/meet/test/web/WebParticipant.java

This reverts commit 64c749921cd3ce0c8a7b4bbcd3fe241b9f48b105.

Revert "Remove deprecated code to disable callstats."

---

src/test/java/org/jitsi/meet/test/pageobjects/web/Toolbar.java

Needed for https://github.com/jitsi/jitsi-meet/pull/12561

fix: rename stats accessibility label

---

src/test/java/org/jitsi/meet/test/LobbyTest.java
src/test/java/org/jitsi/meet/test/pageobjects/web/LobbyScreen.java

This reverts commit 8704cd14b8ae85bc8d22a281124a6ffa51998564.

Revert "fix: Temporary disable lobby tests."

---

src/test/java/org/jitsi/meet/test/AudioVideoModerationTest.java
src/test/java/org/jitsi/meet/test/pageobjects/web/ParticipantsPane.java

Fix tests for new pr: https://github.com/jitsi/jitsi-meet/pull/12977

fix av-moderation tests

---

src/test/java/org/jitsi/meet/test/AudioOnlyTest.java
src/test/java/org/jitsi/meet/test/AvatarTest.java
src/test/java/org/jitsi/meet/test/util/MeetUIUtils.java

The new default avatar is an icon, not an image of an icon

fix(avatar) Fix tests

---

scripts/malleus.sh
src/test/java/org/jitsi/meet/test/MalleusJitsificus.java
src/test/java/org/jitsi/meet/test/base/FailureListener.java
src/test/java/org/jitsi/meet/test/web/WebParticipant.java
src/test/java/org/jitsi/meet/test/web/WebParticipantFactory.java
src/test/java/org/jitsi/meet/test/web/WebParticipantOptions.java

Not moving saveBrowserLogs to utils for now as it depends on outputLogsParentFolder that is handled in FailureListener.

feat: Adds option to malleus to save participants logs.

---

src/test/java/org/jitsi/meet/test/pageobjects/web/InviteDialog.java
src/test/java/org/jitsi/meet/test/pageobjects/web/SecurityDialog.java

See https://github.com/jitsi/jitsi-meet/pull/12969

Update tests related to a11y improvements

---

src/test/java/org/jitsi/meet/test/AudioVideoModerationTest.java
src/test/java/org/jitsi/meet/test/pageobjects/web/BreakoutRoomsList.java

This PR updates breakout-room and av-moderation scripts to test buttons and context menu with improved accessibility after https://github.com/jitsi/jitsi-meet/pull/13669.
These tests also work with the current master branch.

feat: update to test components with improved accessibility

---

doc/grid/Dockerfile

Do not run as root, firefox fails to start.

fix: Fixes custom docker file.

---

src/test/java/org/jitsi/meet/test/pageobjects/web/Toolbar.java

Update tests to match new toolbar labels from [#14161](https://github.com/jitsi/jitsi-meet/pull/14161)

Update tests to new toolbar accessibility label values

---

src/test/java/org/jitsi/meet/test/IFrameAPICommandsTest.java
src/test/resources/desktop/testng.xml

As explained in https://github.com/jitsi/jitsi-meet-torture/commit/759723cef2c8e508058a4fc937e1bba36d7dbc8b youtube shared video is not working. And we are also disabling the non-youtube URLs.

fix(SharedVideoTest): remove.

---

src/test/java/org/jitsi/meet/test/pageobjects/web/ParticipantsPane.java
src/test/java/org/jitsi/meet/test/pageobjects/web/Toolbar.java

Related to https://github.com/jitsi/jitsi-meet/pull/15272

pageobj(ParticipantsPane/Toolbar): updated text for Invite someone label
